version: "3"

services:
  sneakerPosDB:
    image: postgres:15.3
    container_name: sneaker-pos-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./postgres:/var/lib/postgresql/data